# Generated by Django 2.2.8 on 2020-01-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=24, unique=True)),
                ('caught_on', models.DateTimeField(auto_now_add=True)),
                ('species', models.CharField(choices=[('SA', 'Salmon'), ('HA', 'Halibut')], max_length=2)),
                ('location', models.CharField(max_length=20)),
                ('caught_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.FishingCompany')),
            ],
        ),
    ]
