# Generated by Django 2.2.8 on 2020-01-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingcompany',
            name='name',
            field=models.CharField(default='company', max_length=60),
            preserve_default=False,
        ),
    ]
